FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS migrations-base
ARG MIGRATION_NAME=PreProd
WORKDIR /src
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef --version 10.*


FROM migrations-base AS auth
COPY NetNotepad.Contracts/*.csproj NetNotepad.Contracts/
COPY NetNotepad.AuthService/*.csproj NetNotepad.AuthService/

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet restore NetNotepad.AuthService/NetNotepad.AuthService.csproj

COPY NetNotepad.Contracts/. NetNotepad.Contracts/
COPY NetNotepad.AuthService/. NetNotepad.AuthService/.

# Создаём migration от имеющегося prod Snapshot
RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet ef migrations add ${MIGRATION_NAME} \
    --project NetNotepad.AuthService/NetNotepad.AuthService.csproj \
    --startup-project NetNotepad.AuthService/NetNotepad.AuthService.csproj \
    --output-dir Migrations

FROM scratch AS export
COPY --from=auth \
    /src/NetNotepad.AuthService/Migrations \
    /Migrations