FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build

ARG BUILD_CONFIGURATION=Release

WORKDIR /src

# Copy and build all code
COPY NetNotepad.Contracts/*.csproj NetNotepad.Contracts/
COPY NetNotepad.ServiceBase/*.csproj NetNotepad.ServiceBase/
COPY NetNotepad.HttpHandler/*.csproj NetNotepad.HttpHandler/

RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet restore NetNotepad.HttpHandler/NetNotepad.HttpHandler.csproj

COPY NetNotepad.Contracts/. NetNotepad.Contracts/.
COPY NetNotepad.ServiceBase/. NetNotepad.ServiceBase/.
COPY NetNotepad.HttpHandler/. NetNotepad.HttpHandler/.

RUN dotnet publish \
    NetNotepad.HttpHandler/NetNotepad.HttpHandler.csproj \
    -c ${BUILD_CONFIGURATION} \
    -o /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:10.0-alpine AS runtime
WORKDIR /app
COPY --from=build /app/publish .
USER app
HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/health || exit 1
ENTRYPOINT [ "dotnet", "NetNotepad.HttpHandler.dll" ]