x-common:
  restart: &restart
    restart: unless-stopped
  dotnet-security: &dotnet-security
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
  dotnet: &dotnet
    <<:
      - *restart
      - *dotnet-security
  nginx: &nginx
    image: nginx:1.31.5-alpine-slim
    <<: *restart
  postgres: &postgres
    image: postgres:18.6-alpine3.24
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    <<: *restart
  redis: &redis
    image: redis:8.10.1-alpine3.23
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    <<: *restart
  rabbitmq: &rabbitmq
    image: rabbitmq:4.3.6-management-alpine
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_listener", "5672" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    <<: *restart
  environment-auth: &environment-auth
    environment:
      PORT: 8080
      POSTGRESDBHOST: ${AUTH_POSTGRES_HOST_PROXY}
      POSTGRESDBPORT: ${AUTH_POSTGRES_PORT}
      POSTGRESDBNAME: ${AUTH_POSTGRES_NAME}
      POSTGRESDBUSER: ${AUTH_POSTGRES_USER}
      POSTGRESDBPASS: ${AUTH_POSTGRES_PASS}
      HTTP_RABBITMQ_HOST: ${HTTP_RABBITMQ_HOST}
      HTTP_RABBITMQ_PORT: ${HTTP_RABBITMQ_PORT}
      HTTP_RABBITMQ_USER: ${HTTP_RABBITMQ_USER}
      HTTP_RABBITMQ_PASS: ${HTTP_RABBITMQ_PASS}
      REDISHOST: ${AUTH_REDIS_HOST}
      REDISPORT: ${AUTH_REDIS_PORT}
      AUTH_QUEUE_NAME: ${AUTH_QUEUE_NAME}
      AUTH_INT_QUEUE_NAME: ${AUTH_INT_QUEUE_NAME}
      AUTH_RABBITMQ_HOST: ${AUTH_RABBITMQ_HOST}
      AUTH_RABBITMQ_PORT: ${AUTH_RABBITMQ_PORT}
      AUTH_RABBITMQ_USER: ${AUTH_RABBITMQ_USER}
      AUTH_RABBITMQ_PASS: ${AUTH_RABBITMQ_PASS}
      EVENT_NAME: ${EVENT_NAME}
      AUTH_EVENT_NAME: ${AUTH_EVENT_NAME}
  pgbouncer: &pgbouncer
    image: edoburu/pgbouncer:v1.26.0-p0
    healthcheck:
      # test: [ "CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}" ]
      test: [ "CMD-SHELL", "pg_isready -h localhost -p $${DB_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gateway:
    <<: *nginx
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      DOLLAR: $$
    depends_on:
      netnotepad-http:
        condition: service_healthy

  service-gateway:
    <<: *nginx
    ports:
      - "127.0.0.1:8085:80"
    volumes:
      - ./configs/service-nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      DOLLAR: $$
    depends_on:
      pgadmin:
        condition: service_healthy
      rabbitmq-http:
        condition: service_healthy

  pgbouncer-auth:
    <<: *pgbouncer
    environment:
      DB_HOST: ${AUTH_POSTGRES_HOST}
      DB_PORT: ${AUTH_POSTGRES_PORT}
      DB_USER: ${AUTH_POSTGRES_USER}
      DB_PASSWORD: ${AUTH_POSTGRES_PASS}
      DB_NAME: ${AUTH_POSTGRES_NAME}

      POOL_MODE: transaction
      DEFAULT_POOL_SIZE: 4
      MAX_CLIENT_CONN: 100
      QUERY_TIMEOUT: 10
      AUTH_TYPE: scram-sha-256
    depends_on:
      postgres-auth:
        condition: service_healthy

  postgres-auth:
    <<: *postgres
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_NAME}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASS}
    volumes:
      - ./volumes/postgres_auth:/var/lib/postgresql

  redis-auth:
    <<: *redis

  redis-http:
    <<: *redis

  rabbitmq-http:
    <<: *rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: ${HTTP_RABBITMQ_PASS}
      RABBITMQ_DEFAULT_USER: ${HTTP_RABBITMQ_USER}
    volumes:
      - ./configs/rabbitmq-http:/etc/rabbitmq:ro
  rabbitmq-auth:
    <<: *rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: ${AUTH_RABBITMQ_PASS}
      RABBITMQ_DEFAULT_USER: ${AUTH_RABBITMQ_USER}
    volumes:
      - ./configs/rabbitmq-auth:/etc/rabbitmq:ro

  notepad-auth-migration:
    build:
      dockerfile: Dockerfile.auth
      target: migration
    volumes:
      - ./NetNotepad.AuthService/Migrations:/dest/NetNotepad.AuthService/Migrations
    command:
      - cp /src/NetNotepad.AuthService/Migrations /dest/NetNotepad.AuthService/ -r

  netnotepad-auth-external:
    labels:
      - "autoheal=true"
    build:
      dockerfile: Dockerfile.auth
      target: runtime-external
      args:
        BUILD_CONFIGURATION: ${DOTNET_BUILD_CONFIGURATION:-Release}
    <<:
      - *dotnet
      - *environment-auth
    secrets:
      - jwt-secret-pri
      - jwt-secret-pub
    depends_on:
      pgbouncer-auth:
        condition: service_healthy
      redis-auth:
        condition: service_healthy
      rabbitmq-http:
        condition: service_healthy
      rabbitmq-auth:
        condition: service_healthy

  netnotepad-http:
    labels:
      - "autoheal=true"
    build:
      dockerfile: Dockerfile.http
      args:
        BUILD_CONFIGURATION: ${DOTNET_BUILD_CONFIGURATION:-Release}
    <<: *dotnet
    environment:
      PORT: 8080
      REDISHOST: ${HTTP_REDIS_HOST}
      REDISPORT: ${HTTP_REDIS_PORT}
      RABBITMQ_HOST: ${HTTP_RABBITMQ_HOST}
      RABBITMQ_PORT: ${HTTP_RABBITMQ_PORT}
      RABBITMQ_USER: ${HTTP_RABBITMQ_USER}
      RABBITMQ_PASS: ${HTTP_RABBITMQ_PASS}
      AUTH_QUEUE_NAME: ${AUTH_QUEUE_NAME}
      USER_QUEUE_NAME: ${USER_QUEUE_NAME}
      NOTEPAD_QUEUE_NAME: ${NOTEPAD_QUEUE_NAME}
    depends_on:
      redis-http:
        condition: service_healthy
      rabbitmq-http:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:9.18.0
    environment:
      PGADMIN_DEFAULT_HOST: "postgres-auth"
      PGADMIN_DEFAULT_USERNAME: "pgadmin"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_DEFAULT_EMAIL: "example@mail.com"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost/misc/ping >/dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

secrets:
  jwt-secret-pub:
    file: ./secrets/jwt-public.pem
  jwt-secret-pri:
    file: ./secrets/jwt-private.pem
