events { worker_connections 1024; }

http {
    server {
        listen 80;
        proxy_set_header X-Request-ID $request_id;
        proxy_set_header X-Real-IP $remote_addr;

        location /auth/ {
            proxy_pass http://netnotepad-http:8080;
        }
        location /user/ {
            proxy_pass http://netnotepad-http:8080;
        }
        location /notepad/ {
            proxy_pass http://netnotepad-http:8080;
        }
        location /request/ {
            proxy_pass http://netnotepad-http:8080;
        }
    }
}